files:
- compressed: 1440
  start: 32
  uncompressed: 2444
- compressed: 121
  start: 1472
  uncompressed: 166
- compressed: 504
  start: 1600
  uncompressed: 864
- compressed: 1010
  start: 2104
  uncompressed: 1960
name: '00000000'
start: 0
