files:
- compressed: 54
  start: 112
  uncompressed: 120
- compressed: 94
  start: 168
  uncompressed: 272
- compressed: 98
  start: 264
  uncompressed: 312
- compressed: 95
  start: 368
  uncompressed: 280
- compressed: 67
  start: 464
  uncompressed: 152
- compressed: 103
  start: 536
  uncompressed: 312
- compressed: 64
  start: 640
  uncompressed: 144
- compressed: 119
  start: 704
  uncompressed: 440
- compressed: 71
  start: 824
  uncompressed: 152
name: '00000000'
start: 0
